version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000
   

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
   