version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: aasmaan1/backend:latest

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: aasmaan1/frontend:latest
